name: Auto-merge

on:
  workflow_run:
    workflows: ['Terraform']
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.pull_requests[0] }}

    steps:
      - uses: actions/github-script@v6
        id: label-names
        with:
          script: |
            return (await github.rest.pulls.get({
              owner: context.payload.repository.owner.login,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
              repo: context.payload.repository.name
            })).data.labels.map(label => label.name)

      - name: Merge PR
        uses: pascalgn/automerge-action@v0.14.3
        if: ${{ contains(steps.label-names.outputs.result, 'javascript') }}
        env:
          MERGE_LABELS: '' # all
          GITHUB_TOKEN: ${{ github.token }}
