name: Auto-merge

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-20.04
    if: github.actor == 'dependabot[bot]'

    steps:
      - id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: ${{ github.token }}
      - name: Enable auto-merge
        if: steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
